name: build
on: [push]
jobs:
    lint:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v2
            - name: Use Node.js 14
              uses: actions/setup-node@v2
              with:
                  node-version: 14
            - run: yarn install --frozen-lockfile
            - run: yarn format:check
            - run: yarn lint
    build:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v2.3.4
            - name: Set up QEMU
              uses: docker/setup-qemu-action@v2
            - name: Set up Docker Buildx
              uses: docker/setup-buildx-action@v1.3.0
              with:
                  driver: docker
            - name: Build image
              uses: docker/build-push-action@v2.6.1
              with:
                  context: .
                  tags: naviocean/node-typescript-eslint-template:latest
                  load: true
            - name: Run image
              run: docker run naviocean/node-typescript-eslint-template
