name: build
on: [push]
jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2.3.4
      - name: Use Node.js 14.x
        uses: actions/setup-node@v2.1.5
        with:
          node-version: '14.x'
      - run: yarn install --frozen-lockfile
      - run: yarn lint
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2.3.4
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1.3.0
        with:
          driver: docker
#       - name: Login to DockerHub
#         uses: docker/login-action@v1.9.0
#         with:
#           username: ${{ secrets.DOCKER_HUB_USERNAME }}
#           password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}
      
      - name: Build image
        uses: docker/build-push-action@v2.4.0
        with:
          context: .
          tags: naviocean/node-typescript-eslint-template:latest
          load: true
#       - name: Push Docker
#         run: docker push naviocean/node-typescript-eslint-template:latest
      - name: Run image
        run: docker run naviocean/node-typescript-eslint-template
